apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogwebdeployment
  labels:
    app: blogwebdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogwebdeployment
  template:
    metadata:
      labels:
        app: blogwebdeployment
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports: 
          - containerPort: 80
