apiVersion: 'apps/v1'
kind: Deployment
metadata:
  name: blogwebdeployment
  labels:
    apps: blogwebdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: blogwebdeployment
  template:
    metadata:
      labels:
        apps: blogwebdeployment
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports: 
          - containerPort: 80
        
